import React, { createContext, useContext, useState } from 'react';

export type Language = 
  | 'en' | 'zh' | 'ja' | 'es' | 'fr' 
  | 'de' | 'pt' | 'ru' | 'it' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Local First Dictation',
    'hero.tagline': '100% Offline • Privacy First • 4–8x Faster',
    'hero.cta': 'Get Knner',
    'hero.downloadNow': 'Download Now',
    'offline.title': 'Works Without Internet',
    'offline.desc': 'No Wi-Fi? No problem. Knner processes everything locally on your device. Perfect for flights, remote locations, or anywhere with poor connectivity.',
    'privacy.title': 'Your Voice Stays Yours',
    'privacy.desc': 'No API keys. No cloud upload. No data leaves your computer. Your thoughts remain completely private, forever.',
    'efficiency.title': '4–8x Faster Than Typing',
    'efficiency.desc': 'Speak naturally at 150+ words per minute. Let your ideas flow without waiting for your fingers to catch up.',
    'story.title': 'The Story',
    'story.p1': 'I\'m a tech lover who spends hours typing every day. My wrists hurt. My ideas slip away while my fingers struggle to keep up.',
    'story.p2': 'With ADHD, my brain jumps from thought to thought. By the time I finish typing, I\'ve already forgotten what I wanted to say. So many ideas, lost forever.',
    'story.p3': 'That\'s why I built Knner — a dictation tool that works offline, respects privacy, and lets me capture thoughts at the speed of speech.',
    'languages.title': '100 Languages Supported',
    'languages.desc': 'Knner understands you in your preferred language. Switch seamlessly between languages without changing settings.',
    'download.title': 'Download Knner',
    'download.desc': 'Available for Windows, macOS, and Linux. Start dictating in seconds.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Coming Soon',
    'contact.title': 'Get in Touch',
    'contact.desc': 'Have questions or feedback? I\'d love to hear from you.',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacy First',
  },
  zh: {
    'hero.title': 'Knner',
    'hero.subtitle': '本地優先語音輸入',
    'hero.tagline': '100% 離線 • 隱私至上 • 快 4–8 倍',
    'hero.cta': '下載 Knner',
    'hero.downloadNow': '立即下載',
    'offline.title': '無網絡也能使用',
    'offline.desc': '沒有 Wi-Fi？沒問題。Knner 完全在您的設備上本地處理。非常適合飛行、偏遠地區或任何連接不良的地方。',
    'privacy.title': '您的聲音只屬於您',
    'privacy.desc': '無需 API 密鑰。不上傳雲端。數據永不離開您的電腦。您的想法將永遠完全私密。',
    'efficiency.title': '比打字快 4–8 倍',
    'efficiency.desc': '以每分鐘 150+ 字的速度自然說話。讓您的想法自由流動，無需等待手指跟上。',
    'story.title': '故事',
    'story.p1': '我是一個熱愛科技的人，每天花數小時打字。我的手腕疼痛。當手指努力跟上時，我的想法就溜走了。',
    'story.p2': '患有 ADHD，我的大腦從一個想法跳到另一個想法。當我打完字時，我已經忘記了我想說什麼。這麼多想法，永遠失去了。',
    'story.p3': '這就是為什麼我建立了 Knner —— 一個離線工作、尊重隱私、讓我以說話速度捕捉想法的語音輸入工具。',
    'languages.title': '支援 100 種語言',
    'languages.desc': 'Knner 用您偏好的語言理解您。無需更改設置即可在語言之間無縫切換。',
    'download.title': '下載 Knner',
    'download.desc': '適用於 Windows、macOS 和 Linux。幾秒鐘內開始語音輸入。',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': '即將推出',
    'contact.title': '聯絡我',
    'contact.desc': '有問題或反饋？我很樂意聽取您的意見。',
    'contact.email': '電郵',
    'contact.message': '訊息',
    'contact.send': '發送訊息',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': '本地優先 • 隱私至上',
  },
  ja: {
    'hero.title': 'Knner',
    'hero.subtitle': 'ローカルファースト音声入力',
    'hero.tagline': '100% オフライン • プライバシー第一 • 4–8倍高速',
    'hero.cta': 'Knner を入手',
    'hero.downloadNow': '今すぐダウンロード',
    'offline.title': 'インターネットなしで動作',
    'offline.desc': 'Wi-Fi がない？問題ありません。Knner はデバイス上ですべてをローカル処理します。飛行機、リモート地、接続不良の場所に最適です。',
    'privacy.title': 'あなたの声はあなたのもの',
    'privacy.desc': 'API キー不要。クラウドアップロードなし。データはコンピュータから出ません。あなたの考えは完全にプライベートです。',
    'efficiency.title': 'タイピングより 4–8倍高速',
    'efficiency.desc': '自然に 1分間に 150語以上で話せます。指が追いつくのを待たずに、アイデアを自由に流しましょう。',
    'story.title': 'ストーリー',
    'story.p1': '私は毎日何時間もタイピングするテック愛好家です。手首が痛い。指が追いつくのに苦労している間に、アイデアが逃げていきます。',
    'story.p2': 'ADHD のため、私の脳は考えから考えへ飛びます。タイピングを終える頃には、何を言いたかったか忘れています。多くのアイデアが永遠に失われます。',
    'story.p3': 'だから私は Knner を作りました — オフラインで動作し、プライバシーを尊重し、話す速度で考えを捉える音声入力ツールです。',
    'languages.title': '100言語をサポート',
    'languages.desc': 'Knner はお好みの言語であなたを理解します。設定を変更せずに言語間をシームレスに切り替えられます。',
    'download.title': 'Knner をダウンロード',
    'download.desc': 'Windows、macOS、Linux で利用可能。数秒で音声入力を開始。',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': '近日公開',
    'contact.title': 'お問い合わせ',
    'contact.desc': '質問やフィードバックがありますか？お聞かせください。',
    'contact.email': 'メール',
    'contact.message': 'メッセージ',
    'contact.send': '送信',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'ローカルファースト • プライバシー第一',
  },
  es: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Dictado Local First',
    'hero.tagline': '100% Offline • Privacidad Primero • 4–8x Más Rápido',
    'hero.cta': 'Obtener Knner',
    'hero.downloadNow': 'Descargar Ahora',
    'offline.title': 'Funciona Sin Internet',
    'offline.desc': '¿Sin Wi-Fi? No hay problema. Knner procesa todo localmente en tu dispositivo. Perfecto para vuelos, ubicaciones remotas o cualquier lugar con mala conectividad.',
    'privacy.title': 'Tu Voz Te Pertenece',
    'privacy.desc': 'Sin claves API. Sin subida a la nube. Tus datos nunca salen de tu computadora. Tus pensamientos permanecen completamente privados, para siempre.',
    'efficiency.title': '4–8x Más Rápido Que Escribir',
    'efficiency.desc': 'Habla naturalmente a 150+ palabras por minuto. Deja que tus ideas fluyan sin esperar a que tus dedos alcancen.',
    'story.title': 'La Historia',
    'story.p1': 'Soy un amante de la tecnología que pasa horas escribiendo cada día. Me duelen las muñecas. Mis ideas se escapan mientras mis dedos luchan por seguir el ritmo.',
    'story.p2': 'Con TDAH, mi cerebro salta de pensamiento en pensamiento. Para cuando termino de escribir, ya olvidé lo que quería decir. Tantas ideas, perdidas para siempre.',
    'story.p3': 'Por eso construí Knner — una herramienta de dictado que funciona offline, respeta la privacidad y me permite capturar pensamientos a la velocidad del habla.',
    'languages.title': '100 Idiomas Soportados',
    'languages.desc': 'Knner te entiende en tu idioma preferido. Cambia entre idiomas sin modificar la configuración.',
    'download.title': 'Descargar Knner',
    'download.desc': 'Disponible para Windows, macOS y Linux. Comienza a dictar en segundos.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Próximamente',
    'contact.title': 'Contacto',
    'contact.desc': '¿Preguntas o comentarios? Me encantaría saber de ti.',
    'contact.email': 'Email',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacidad Primero',
  },
  fr: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Dictée Local First',
    'hero.tagline': '100% Hors Ligne • Confidentialité • 4–8x Plus Rapide',
    'hero.cta': 'Obtenir Knner',
    'hero.downloadNow': 'Télécharger Maintenant',
    'offline.title': 'Fonctionne Sans Internet',
    'offline.desc': 'Pas de Wi-Fi ? Pas de problème. Knner traite tout localement sur votre appareil. Parfait pour les vols, les endroits isolés ou partout où la connexion est mauvaise.',
    'privacy.title': 'Votre Voix Vous Appartient',
    'privacy.desc': 'Pas de clés API. Pas de téléchargement cloud. Aucune donnée ne quitte votre ordinateur. Vos pensées restent complètement privées, pour toujours.',
    'efficiency.title': '4–8x Plus Rapide Que Taper',
    'efficiency.desc': 'Parlez naturellement à 150+ mots par minute. Laissez vos idées couler sans attendre que vos doigts suivent.',
    'story.title': 'L\'Histoire',
    'story.p1': 'Je suis un amateur de technologie qui passe des heures à taper chaque jour. Mes poignets me font mal. Mes idées s\'échappent pendant que mes doigts peinent à suivre.',
    'story.p2': 'Avec le TDAH, mon cerveau saute d\'une pensée à l\'autre. Au moment où j\'ai fini de taper, j\'ai déjà oublié ce que je voulais dire. Tant d\'idées, perdues pour toujours.',
    'story.p3': 'C\'est pourquoi j\'ai construit Knner — un outil de dictée qui fonctionne hors ligne, respecte la confidentialité et me permet de capturer les pensées à la vitesse de la parole.',
    'languages.title': '100 Langues Supportées',
    'languages.desc': 'Knner vous comprend dans votre langue préférée. Passez d\'une langue à l\'autre sans changer les paramètres.',
    'download.title': 'Télécharger Knner',
    'download.desc': 'Disponible pour Windows, macOS et Linux. Commencez à dicter en quelques secondes.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Bientôt',
    'contact.title': 'Contact',
    'contact.desc': 'Des questions ou des commentaires ? J\'aimerais avoir de vos nouvelles.',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Envoyer',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Confidentialité',
  },
  de: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Local First Diktat',
    'hero.tagline': '100% Offline • Datenschutz • 4–8x Schneller',
    'hero.cta': 'Knner Holen',
    'hero.downloadNow': 'Jetzt herunterladen',
    'offline.title': 'Funktioniert Ohne Internet',
    'offline.desc': 'Kein Wi-Fi? Kein Problem. Knner verarbeitet alles lokal auf Ihrem Gerät. Perfekt für Flüge, abgelegene Orte oder überall mit schlechter Verbindung.',
    'privacy.title': 'Ihre Stimme Gehört Ihnen',
    'privacy.desc': 'Keine API-Schlüssel. Kein Cloud-Upload. Keine Daten verlassen Ihren Computer. Ihre Gedanken bleiben für immer völlig privat.',
    'efficiency.title': '4–8x Schneller Als Tippen',
    'efficiency.desc': 'Sprechen Sie natürlich mit 150+ Wörtern pro Minute. Lassen Sie Ihre Ideen fließen, ohne auf Ihre Finger zu warten.',
    'story.title': 'Die Geschichte',
    'story.p1': 'Ich bin ein Technikliebhaber, der täglich stundenlang tippt. Meine Handgelenke tun weh. Meine Ideen entwischen, während meine Finger mühsam nachkommen.',
    'story.p2': 'Mit ADHS springt mein Gehirn von Gedanke zu Gedanke. Wenn ich mit dem Tippen fertig bin, habe ich bereits vergessen, was ich sagen wollte. So viele Ideen, für immer verloren.',
    'story.p3': 'Deshalb habe ich Knner gebaut — ein Diktierwerkzeug, das offline funktioniert, den Datenschutz respektiert und mir erlaubt, Gedanken mit Sprechgeschwindigkeit zu erfassen.',
    'languages.title': '100 Sprachen Unterstützt',
    'languages.desc': 'Knner versteht Sie in Ihrer bevorzugten Sprache. Wechseln Sie nahtlos zwischen Sprachen ohne Einstellungen zu ändern.',
    'download.title': 'Knner Herunterladen',
    'download.desc': 'Verfügbar für Windows, macOS und Linux. Beginnen Sie in Sekunden zu diktieren.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Demnächst',
    'contact.title': 'Kontakt',
    'contact.desc': 'Fragen oder Feedback? Ich würde gerne von Ihnen hören.',
    'contact.email': 'Email',
    'contact.message': 'Nachricht',
    'contact.send': 'Senden',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Datenschutz',
  },
  pt: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Ditado Local First',
    'hero.tagline': '100% Offline • Privacidade • 4–8x Mais Rápido',
    'hero.cta': 'Obter Knner',
    'hero.downloadNow': 'Baixar Agora',
    'offline.title': 'Funciona Sem Internet',
    'offline.desc': 'Sem Wi-Fi? Sem problema. Knner processa tudo localmente no seu dispositivo. Perfeito para voos, locais remotos ou qualquer lugar com conexão ruim.',
    'privacy.title': 'Sua Voz É Sua',
    'privacy.desc': 'Sem chaves API. Sem upload na nuvem. Nenhum dado sai do seu computador. Seus pensamentos permanecem completamente privados, para sempre.',
    'efficiency.title': '4–8x Mais Rápido Que Digitar',
    'efficiency.desc': 'Fale naturalmente a 150+ palavras por minuto. Deixe suas ideias fluírem sem esperar seus dedos acompanharem.',
    'story.title': 'A História',
    'story.p1': 'Sou um amante de tecnologia que passa horas digitando todos os dias. Meus pulsos doem. Minhas ideias escapam enquanto meus dedos lutam para acompanhar.',
    'story.p2': 'Com TDAH, meu cérebro salta de pensamento em pensamento. Quando termino de digitar, já esqueci o que queria dizer. Tantas ideias, perdidas para sempre.',
    'story.p3': 'Por isso construí o Knner — uma ferramenta de ditado que funciona offline, respeita a privacidade e me permite capturar pensamentos na velocidade da fala.',
    'languages.title': '100 Idiomas Suportados',
    'languages.desc': 'Knner entende você em seu idioma preferido. Alterne entre idiomas sem alterar configurações.',
    'download.title': 'Baixar Knner',
    'download.desc': 'Disponível para Windows, macOS e Linux. Comece a ditar em segundos.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Em Breve',
    'contact.title': 'Contato',
    'contact.desc': 'Perguntas ou feedback? Adoraria ouvir de você.',
    'contact.email': 'Email',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacidade',
  },
  ru: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Локальный Диктант',
    'hero.tagline': '100% Офлайн • Конфиденциальность • В 4–8 раз Быстрее',
    'hero.cta': 'Получить Knner',
    'hero.downloadNow': 'Скачать сейчас',
    'offline.title': 'Работает Без Интернета',
    'offline.desc': 'Нет Wi-Fi? Нет проблемы. Knner обрабатывает всё локально на вашем устройстве. Идеально для полётов, удалённых мест или где плохая связь.',
    'privacy.title': 'Ваш Голос Принадлежит Вам',
    'privacy.desc': 'Нет API-ключей. Нет загрузки в облако. Данные не покидают ваш компьютер. Ваши мысли остаются полностью приватными, навсегда.',
    'efficiency.title': 'В 4–8 раз Быстрее Печати',
    'efficiency.desc': 'Говорите естественно со скоростью 150+ слов в минуту. Позвольте вашим идеям течь, не дожидаясь пальцев.',
    'story.title': 'История',
    'story.p1': 'Я любитель технологий, который каждый день часами печатает. У меня болят запястья. Мои идеи ускользают, пока пальцы с трудом поспевают.',
    'story.p2': 'С СДВГ мой мозг прыгает от мысли к мысли. Когда я заканчиваю печатать, я уже забыл, что хотел сказать. Столько идей, потерянных навсегда.',
    'story.p3': 'Поэтому я создал Knner — инструмент диктовки, который работает офлайн, уважает конфиденциальность и позволяет мне захватывать мысли со скоростью речи.',
    'languages.title': '100 Языков Поддерживается',
    'languages.desc': 'Knner понимает вас на вашем предпочтительном языке. Переключайтесь между языками без изменения настроек.',
    'download.title': 'Скачать Knner',
    'download.desc': 'Доступно для Windows, macOS и Linux. Начните диктовать за секунды.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Скоро',
    'contact.title': 'Контакт',
    'contact.desc': 'Вопросы или отзывы? Буду рад услышать вас.',
    'contact.email': 'Email',
    'contact.message': 'Сообщение',
    'contact.send': 'Отправить',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Конфиденциальность',
  },
  it: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Dettato Local First',
    'hero.tagline': '100% Offline • Privacy • 4–8x Più Veloce',
    'hero.cta': 'Ottieni Knner',
    'hero.downloadNow': 'Scarica Ora',
    'offline.title': 'Funziona Senza Internet',
    'offline.desc': 'Niente Wi-Fi? Nessun problema. Knner elabora tutto localmente sul tuo dispositivo. Perfetto per voli, luoghi remoti o ovunque la connessione sia scarsa.',
    'privacy.title': 'La Tua Voce È Tua',
    'privacy.desc': 'Nessuna chiave API. Nessun caricamento cloud. Nessun dato lascia il tuo computer. I tuoi pensieri rimangono completamente privati, per sempre.',
    'efficiency.title': '4–8x Più Veloce Della Digitazione',
    'efficiency.desc': 'Parla naturalmente a 150+ parole al minuto. Lascia che le tue idee scorrano senza aspettare che le dita ti raggiungano.',
    'story.title': 'La Storia',
    'story.p1': 'Sono un amante della tecnologia che passa ore a digitare ogni giorno. Mi fanno male i polsi. Le mie idee scappano mentre le dita faticano a stare al passo.',
    'story.p2': 'Con l\'ADHD, il mio cervello salta da un pensiero all\'altro. Quando finisco di digitare, ho già dimenticato cosa volevo dire. Tante idee, perse per sempre.',
    'story.p3': 'Ecco perché ho costruito Knner — uno strumento di dettato che funziona offline, rispetta la privacy e mi permette di catturare i pensieri alla velocità della parola.',
    'languages.title': '100 Lingue Supportate',
    'languages.desc': 'Knner ti capisce nella tua lingua preferita. Passa da una lingua all\'altra senza modificare le impostazioni.',
    'download.title': 'Scarica Knner',
    'download.desc': 'Disponibile per Windows, macOS e Linux. Inizia a dettare in pochi secondi.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Prossimamente',
    'contact.title': 'Contatto',
    'contact.desc': 'Domande o feedback? Mi piacerebbe sentirti.',
    'contact.email': 'Email',
    'contact.message': 'Messaggio',
    'contact.send': 'Invia',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacy',
  },
  ko: {
    'hero.title': 'Knner',
    'hero.subtitle': '로컬 퍼스트 음성 입력',
    'hero.tagline': '100% 오프라인 • 개인정보 보호 • 4–8배 빠름',
    'hero.cta': 'Knner 받기',
    'hero.downloadNow': '지금 다운로드',
    'offline.title': '인터넷 없이 작동',
    'offline.desc': 'Wi-Fi가 없어도 문제없습니다. Knner는 기기에서 모든 것을 로컬로 처리합니다. 비행, 원격 위치 또는 연결이 불량한 곳에 완벽합니다.',
    'privacy.title': '당신의 목소리는 당신의 것',
    'privacy.desc': 'API 키 없음. 클라우드 업로드 없음. 데이터가 컴퓨터를 떠나지 않습니다. 당신의 생각은 영원히 완전히 비공개로 유지됩니다.',
    'efficiency.title': '타이핑보다 4–8배 빠름',
    'efficiency.desc': '분당 150단어 이상으로 자연스럽게 말하세요. 손가락을 기다리지 않고 아이디어가 자유롭게 흐르게 하세요.',
    'story.title': '이야기',
    'story.p1': '저는 매일 수 시간 동안 타이핑하는 기술 애호가입니다. 손목이 아픕니다. 손가락이 따라가기 위해 힘쓰는 동안 아이디어가 사라집니다.',
    'story.p2': 'ADHD로 인해 제 뇌는 생각에서 생각으로 뛰어다닙니다. 타이핑을 마칠 때쯤이면 이미 무엇을 말하려 했는지 잊어버렸습니다. 너무 많은 아이디어가 영원히 사라졌습니다.',
    'story.p3': '그래서 저는 Knner를 만들었습니다 — 오프라인으로 작동하고, 개인정보를 존중하며, 말하는 속도로 생각을 포착할 수 있는 음성 입력 도구입니다.',
    'languages.title': '100개 언어 지원',
    'languages.desc': 'Knner는 선호하는 언어로 당신을 이해합니다. 설정을 변경하지 않고 언어 간에 원활하게 전환하세요.',
    'download.title': 'Knner 다운로드',
    'download.desc': 'Windows, macOS 및 Linux에서 사용 가능합니다. 몇 초 만에 음성 입력을 시작하세요.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': '곧 출시',
    'contact.title': '연락처',
    'contact.desc': '질문이나 피드백이 있으신가요? 연락을 기다리겠습니다.',
    'contact.email': '이메일',
    'contact.message': '메시지',
    'contact.send': '병내기',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': '로컬 퍼스트 • 개인정보 보호',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
