import React, { createContext, useContext, useState } from 'react';

export type Language = 
  | 'en' | 'zh' | 'ja' | 'es' | 'fr' 
  | 'de' | 'pt' | 'ru' | 'it' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Local First Dictation',
    'hero.tagline': '100% Offline • Privacy First • 4–8x Faster',
    'hero.cta': 'Get Knner',
    'hero.downloadNow': 'Download Now',
    'offline.title': 'Works Without Internet',
    'offline.desc': 'No Wi-Fi? No problem. Knner processes everything locally on your device. Perfect for flights, remote locations, or anywhere with poor connectivity.',
    'privacy.title': 'Your Voice Stays Yours',
    'privacy.desc': 'No API keys. No cloud upload. No data leaves your computer. Your thoughts remain completely private, forever.',
    'efficiency.title': '4–8x Faster Than Typing',
    'efficiency.desc': 'Speak naturally at 150+ words per minute. Let your ideas flow without waiting for your fingers to catch up.',
    'story.title': 'The Story',
    'story.p1': 'I\'m a tech lover who spends hours typing every day. My wrists hurt. My ideas slip away while my fingers struggle to keep up.',
    'story.p2': 'With ADHD, my brain jumps from thought to thought. When I have a thought, hands on the keyboard, I\'ve already forgotten what I was saying. So many ideas, lost forever.',
    'story.p3': 'That\'s why I built Knner — a dictation tool that works offline, respects privacy, and lets me capture thoughts at the speed of speech.',
    'languages.title': '100 Languages Supported',
    'languages.desc': 'Knner understands you in your preferred language. Switch seamlessly between languages without changing settings.',
    'download.title': 'Download Knner',
    'download.desc': 'Available for Windows, macOS, and Linux. Start dictating in seconds.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Coming Soon',
    'contact.title': 'Get in Touch',
    'contact.desc': 'Have questions or feedback? I\'d love to hear from you.',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacy First',
    'social.users': '10,000+ Worldwide Users',
    'social.languages': '100+ Languages Supported',
    'social.offline': '100% Works Offline',
    'social.rating': '4.9 User Rating',
    'social.testimonials': 'What Users Say',
    'social.localData': 'Local Data Storage',
    'social.noCloud': 'Never Uploads to Cloud',
    'social.madeHK': 'Made in Hong Kong',
    'social.securePayment': 'Secure Payment',
    'screenshots.title': 'Screenshot Preview',
    'screenshots.desc': "See how Knner boosts your productivity",
    'screenshots.main': 'Main Interface',
    'screenshots.mainDesc': 'Clean interface, one-tap recording',
    'screenshots.settings': 'Settings Page',
    'screenshots.settingsDesc': 'Customize language, hotkeys, shortcuts',
    'screenshots.usage': 'Usage Tracking',
    'screenshots.usageDesc': 'Clear usage limits display',
    'screenshots.floating': 'Floating Ball Mode',
    'screenshots.floatingDesc': 'Record anytime, stays out of the way',
    'screenshots.screenshotTip': 'Recommended screenshot size: 1920x1080 (16:9)',
    'video.title': 'See How Fast It Is',
    'video.desc': "30 seconds to understand Knner's power",
    'video.play': '▶ Click to play 30s intro video',
    'video.script': 'Video Script (30 seconds)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'Works perfectly offline. Essential tool for my daily standups and documentation.',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': 'Perfect for taking lecture notes. I can capture everything the professor says without missing a word.',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'Love this app! It has completely replaced typing for me. The accuracy is amazing.',
  },
  zh: {
    'hero.title': 'Knner',
    'hero.subtitle': '本地優先語音輸入',
    'hero.tagline': '100% 離線 • 隱私至上 • 快 4–8 倍',
    'hero.cta': '下載 Knner',
    'hero.downloadNow': '立即下載',
    'offline.title': '無網絡也能使用',
    'offline.desc': '沒有 Wi-Fi？沒問題。Knner 完全在您的設備上本地處理。非常適合飛行、偏遠地區或任何連接不良的地方。',
    'privacy.title': '您的聲音只屬於您',
    'privacy.desc': '無需 API 密鑰。不上傳雲端。數據永不離開您的電腦。您的想法將永遠完全私密。',
    'efficiency.title': '比打字快 4–8 倍',
    'efficiency.desc': '以每分鐘 150+ 字的速度自然說話。讓您的想法自由流動，無需等待手指跟上。',
    'story.title': '故事',
    'story.p1': '我是一個熱愛科技的人，每天花數小時打字。我的手腕疼痛。當手指努力跟上時，我的想法就溜走了。',
    'story.p2': '患有 ADHD，我的大腦從一個想法跳到另一個想法。當我有一個想法，雙手在鍵盤上面，已經忘記了自己想說什麼。這麼多想法，永遠失去了。',
    'story.p3': '這就是為什麼我建立了 Knner —— 一個離線工作、尊重隱私、讓我以說話速度捕捉想法的語音輸入工具。',
    'languages.title': '支援 100 種語言',
    'languages.desc': 'Knner 用您偏好的語言理解您。無需更改設置即可在語言之間無縫切換。',
    'download.title': '下載 Knner',
    'download.desc': '適用於 Windows、macOS 和 Linux。幾秒鐘內開始語音輸入。',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': '即將推出',
    'contact.title': '聯絡我',
    'contact.desc': '有問題或反饋？我很樂意聽取您的意見。',
    'contact.email': '電郵',
    'contact.message': '訊息',
    'contact.send': '發送訊息',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': '本地優先 • 隱私至上',
    'social.users': '全球用戶 10,000+',
    'social.languages': '支援語言',
    'social.offline': '離線可用',
    'social.rating': '用戶評分',
    'social.testimonials': '用戶點評',
    'social.localData': '資料本地儲存',
    'social.noCloud': '不上傳雲端',
    'social.madeHK': '香港開發',
    'social.securePayment': '安全支付',
    'screenshots.title': '截圖預覽',
    'screenshots.desc': '了解 Knner 如何提升你的工作效率',
    'screenshots.main': '主要介面',
    'screenshots.mainDesc': '簡潔易用，一鍵錄音',
    'screenshots.settings': '設定頁面',
    'screenshots.settingsDesc': '自訂語言、按鍵、速記',
    'screenshots.usage': '用量追蹤',
    'screenshots.usageDesc': '清晰顯示已用 / 剩餘額度',
    'screenshots.floating': '悬浮球模式',
    'screenshots.floatingDesc': '隨時錄音，不阻礙',
    'screenshots.screenshotTip': '截圖尺寸建議：1920x1080 (16:9)',
    'video.title': '看看有多快',
    'video.desc': '30秒帶你了解 Knner 的強大功能',
    'video.play': '▶ 點擊播放 30秒介紹影片',
    'video.script': '影片腳本（30秒）',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': '真係好方便！老細開會我再都唔使抄到手軟，直接語音輸入就自動變文字',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': '用咗三個月，打字量少咗70%！又多時間寫多啲稿',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': '考試複習必備！可以快速記低重點，溫書效率高咗好多',
  },
  ja: {
    'hero.title': 'Knner',
    'hero.subtitle': 'ローカルファースト音声入力',
    'hero.tagline': '100% オフライン • プライバシー第一 • 4–8倍高速',
    'hero.cta': 'Knner を入手',
    'hero.downloadNow': '今すぐダウンロード',
    'offline.title': 'インターネットなしで動作',
    'offline.desc': 'Wi-Fi がない？問題ありません。Knner はデバイス上ですべてをローカル処理します。飛行機、リモート地、接続不良の場所に最適です。',
    'privacy.title': 'あなたの声はあなたのもの',
    'privacy.desc': 'API キー不要。クラウドアップロードなし。データはコンピュータから出ません。あなたの考えは完全にプライベートです。',
    'efficiency.title': 'タイピングより 4–8倍高速',
    'efficiency.desc': '自然に 1分間に 150語以上で話せます。指が追いつくのを待たずに、アイデアを自由に流しましょう。',
    'story.title': 'ストーリー',
    'story.p1': '私は毎日何時間もタイピングするテック愛好家です。手首が痛い。指が追いつくのに苦労している間に、アイデアが逃げていきます。',
    'story.p2': 'ADHD のため、私の脳は考えから考えへ飛びます。考えが浮かんだとき、キーボードに手を置いているうちに、何を言おうとしていたか忘れてしまいます。多くのアイデアが永遠に失われます。',
    'story.p3': 'だから私は Knner を作りました — オフラインで動作し、プライバシーを尊重し、話す速度で考えを捉える音声入力ツールです。',
    'languages.title': '100言語をサポート',
    'languages.desc': 'Knner はお好みの言語であなたを理解します。設定を変更せずに言語間をシームレスに切り替えられます。',
    'download.title': 'Knner をダウンロード',
    'download.desc': 'Windows、macOS、Linux で利用可能。数秒で音声入力を開始。',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': '近日公開',
    'contact.title': 'お問い合わせ',
    'contact.desc': '質問やフィードバックがありますか？お聞かせください。',
    'contact.email': 'メール',
    'contact.message': 'メッセージ',
    'contact.send': '送信',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'ローカルファースト • プライバシー第一',
    'social.users': '世界中のユーザー 10,000+',
    'social.languages': '100以上の言語対応',
    'social.offline': '100% オフライン対応',
    'social.rating': 'ユーザー評価 4.9',
    'social.testimonials': 'ユーザーの声',
    'social.localData': 'ローカルデータ保存',
    'social.noCloud': 'クラウドにアップロードしない',
    'social.madeHK': '香港開発',
    'social.securePayment': '安全な決済',
    'screenshots.title': 'スクリーンショット',
    'screenshots.desc': 'Knnerが生産性を上げる仕組み',
    'screenshots.main': 'メイン画面',
    'screenshots.mainDesc': 'シンプルでワンプッシュ録音',
    'screenshots.settings': '設定ページ',
    'screenshots.settingsDesc': '言語・ホットキー・ショートカット設定',
    'screenshots.usage': '使用量表示',
    'screenshots.usageDesc': '残り回数がひと目でわかる',
    'screenshots.floating': 'フローティング-ballモード',
    'screenshots.floatingDesc': 'いつでも録音、邪魔にならない',
    'screenshots.screenshotTip': '推奨サイズ：1920x1080 (16:9)',
    'video.title': 'どのくらい速いか見る',
    'video.desc': '30秒でKnnerの性能を理解する',
    'video.play': '▶ 30秒紹介動画を再生',
    'video.script': '動画台本（30秒）',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'オフラインでも使えるのが最高！外出先でも正確に文字起こししてくれます',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': '講義ノートを取るのに最適。学生的にも先生的にもおすすめのツールです',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'タイピング厌烦になったらこれ。話すだけで文章になるなんて革命的！',
  },
  es: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Dictado Local First',
    'hero.tagline': '100% Offline • Privacidad Primero • 4–8x Más Rápido',
    'hero.cta': 'Obtener Knner',
    'hero.downloadNow': 'Descargar Ahora',
    'offline.title': 'Funciona Sin Internet',
    'offline.desc': '¿Sin Wi-Fi? No hay problema. Knner procesa todo localmente en tu dispositivo. Perfecto para vuelos, ubicaciones remotas o cualquier lugar con mala conectividad.',
    'privacy.title': 'Tu Voz Te Pertenece',
    'privacy.desc': 'Sin claves API. Sin subida a la nube. Tus datos nunca salen de tu computadora. Tus pensamientos permanecen completamente privados, para siempre.',
    'efficiency.title': '4–8x Más Rápido Que Escribir',
    'efficiency.desc': 'Habla naturalmente a 150+ palabras por minuto. Deja que tus ideas fluyan sin esperar a que tus dedos alcancen.',
    'story.title': 'La Historia',
    'story.p1': 'Soy un amante de la tecnología que pasa horas escribiendo cada día. Me duelen las muñecas. Mis ideas se escapan mientras mis dedos luchan por seguir el ritmo.',
    'story.p2': 'Con TDAH, mi cerebro salta de pensamiento en pensamiento. Cuando tengo un pensamiento, con las manos en el teclado, ya he olvidado lo que estaba diciendo. Tantas ideas, perdidas para siempre.',
    'story.p3': 'Por eso construí Knner — una herramienta de dictado que funciona offline, respeta la privacidad y me permite capturar pensamientos a la velocidad del habla.',
    'languages.title': '100 Idiomas Soportados',
    'languages.desc': 'Knner te entiende en tu idioma preferido. Cambia entre idiomas sin modificar la configuración.',
    'download.title': 'Descargar Knner',
    'download.desc': 'Disponible para Windows, macOS y Linux. Comienza a dictar en segundos.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Próximamente',
    'contact.title': 'Contacto',
    'contact.desc': '¿Preguntas o comentarios? Me encantaría saber de ti.',
    'contact.email': 'Email',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacidad Primero',
    'social.users': '10.000+ usuarios en todo el mundo',
    'social.languages': 'Más de 100 idiomas soportados',
    'social.offline': '100% funciona sin conexión',
    'social.rating': 'Valoración 4.9 usuarios',
    'social.testimonials': 'Lo que dicen los usuarios',
    'social.localData': 'Almacenamiento local de datos',
    'social.noCloud': 'Nunca sube a la nube',
    'social.madeHK': 'Hecho en Hong Kong',
    'social.securePayment': 'Pago seguro',
    'screenshots.title': 'Vista previa de capturas',
    'screenshots.desc': 'Mira cómo Knner aumenta tu productividad',
    'screenshots.main': 'Interfaz principal',
    'screenshots.mainDesc': 'Interfaz limpia, grabación con un toque',
    'screenshots.settings': 'Página de ajustes',
    'screenshots.settingsDesc': 'Personaliza idioma, atajos de teclado',
    'screenshots.usage': 'Seguimiento de uso',
    'screenshots.usageDesc': 'Visualización clara de límites',
    'screenshots.floating': 'Modo bola flotante',
    'screenshots.floatingDesc': 'Graba en cualquier momento, sin estorbar',
    'screenshots.screenshotTip': 'Tamaño recomendado: 1920x1080 (16:9)',
    'video.title': 'Mira qué tan rápido es',
    'video.desc': '30 segundos para entender el poder de Knner',
    'video.play': '▶ Clic para reproducir video de 30s',
    'video.script': 'Guion del video (30 segundos)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': '¡Increíble! Las reuniones ahora son mucho más eficientes. Dictó todo mientras hablo.',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': 'Perfecto para tomar notas en clase. Puedo seguir la lección sin perder ningún detalle.',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'Me encanta esta app. Ha reemplazado completamente mi teclado para escribir artículos.',
  },
  fr: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Dictée Local First',
    'hero.tagline': '100% Hors Ligne • Confidentialité • 4–8x Plus Rapide',
    'hero.cta': 'Obtenir Knner',
    'hero.downloadNow': 'Télécharger Maintenant',
    'offline.title': 'Fonctionne Sans Internet',
    'offline.desc': 'Pas de Wi-Fi ? Pas de problème. Knner traite tout localement sur votre appareil. Parfait pour les vols, les endroits isolés ou partout où la connexion est mauvaise.',
    'privacy.title': 'Votre Voix Vous Appartient',
    'privacy.desc': 'Pas de clés API. Pas de téléchargement cloud. Aucune donnée ne quitte votre ordinateur. Vos pensées restent complètement privées, pour toujours.',
    'efficiency.title': '4–8x Plus Rapide Que Taper',
    'efficiency.desc': 'Parlez naturellement à 150+ mots par minute. Laissez vos idées couler sans attendre que vos doigts suivent.',
    'story.title': 'L\'Histoire',
    'story.p1': 'Je suis un amateur de technologie qui passe des heures à taper chaque jour. Mes poignets me font mal. Mes idées s\'échappent pendant que mes doigts peinent à suivre.',
    'story.p2': 'Avec le TDAH, mon cerveau saute d\'une pensée à l\'autre. Quand j\'ai une pensée, les mains sur le clavier, j\'ai déjà oublié ce que je disais. Tant d\'idées, perdues pour toujours.',
    'story.p3': 'C\'est pourquoi j\'ai construit Knner — un outil de dictée qui fonctionne hors ligne, respecte la confidentialité et me permet de capturer les pensées à la vitesse de la parole.',
    'languages.title': '100 Langues Supportées',
    'languages.desc': 'Knner vous comprend dans votre langue préférée. Passez d\'une langue à l\'autre sans changer les paramètres.',
    'download.title': 'Télécharger Knner',
    'download.desc': 'Disponible pour Windows, macOS et Linux. Commencez à dicter en quelques secondes.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Bientôt',
    'contact.title': 'Contact',
    'contact.desc': 'Des questions ou des commentaires ? J\'aimerais avoir de vos nouvelles.',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Envoyer',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Confidentialité',
    'social.users': '10 000+ utilisateurs dans le monde',
    'social.languages': 'Plus de 100 langues prises en charge',
    'social.offline': '100% fonctionne hors ligne',
    'social.rating': 'Note 4,9 utilisateurs',
    'social.testimonials': 'Ce que disent les utilisateurs',
    'social.localData': 'Stockage local des données',
    'social.noCloud': 'Jamais uploadé vers le cloud',
    'social.madeHK': 'Fabriqué à Hong Kong',
    'social.securePayment': 'Paiement sécurisé',
    'screenshots.title': 'Aperçu des captures',
    'screenshots.desc': 'Découvrez comment Knner booste votre productivité',
    'screenshots.main': 'Interface principale',
    'screenshots.mainDesc': 'Interface épurée, enregistrement en un clic',
    'screenshots.settings': 'Page des paramètres',
    'screenshots.settingsDesc': 'Personnaliser langue, raccourcis, touches',
    'screenshots.usage': 'Suivi d\'utilisation',
    'screenshots.usageDesc': 'Affichage clair des limites',
    'screenshots.floating': 'Mode bulle flottante',
    'screenshots.floatingDesc': 'Enregistrez à tout moment, sans gêner',
    'screenshots.screenshotTip': 'Taille recommandée : 1920x1080 (16:9)',
    'video.title': 'Découvrez la rapidité',
    'video.desc': '30 secondes pour comprendre Knner',
    'video.play': '▶ Cliquez pour voir la vidéo 30s',
    'video.script': 'Script vidéo (30 secondes)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'Incroyable ! Les réunions sont devenues tellement plus efficaces. Je dicte tout en parlant.',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': 'Parfait pour prendre des notes en cours. Je peux suivre le professeur sans perdre un seul détail.',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'J\'adore cette app. Elle a complètement remplacé mon clavier pour écrire des articles.',
  },
  de: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Local First Diktat',
    'hero.tagline': '100% Offline • Datenschutz • 4–8x Schneller',
    'hero.cta': 'Knner Holen',
    'hero.downloadNow': 'Jetzt herunterladen',
    'offline.title': 'Funktioniert Ohne Internet',
    'offline.desc': 'Kein Wi-Fi? Kein Problem. Knner verarbeitet alles lokal auf Ihrem Gerät. Perfekt für Flüge, abgelegene Orte oder überall mit schlechter Verbindung.',
    'privacy.title': 'Ihre Stimme Gehört Ihnen',
    'privacy.desc': 'Keine API-Schlüssel. Kein Cloud-Upload. Keine Daten verlassen Ihren Computer. Ihre Gedanken bleiben für immer völlig privat.',
    'efficiency.title': '4–8x Schneller Als Tippen',
    'efficiency.desc': 'Sprechen Sie natürlich mit 150+ Wörtern pro Minute. Lassen Sie Ihre Ideen fließen, ohne auf Ihre Finger zu warten.',
    'story.title': 'Die Geschichte',
    'story.p1': 'Ich bin ein Technikliebhaber, der täglich stundenlang tippt. Meine Handgelenke tun weh. Meine Ideen entwischen, während meine Finger mühsam nachkommen.',
    'story.p2': 'Mit ADHS springt mein Gehirn von Gedanke zu Gedanke. Wenn ich einen Gedanken habe, Hände auf der Tastatur, habe ich bereits vergessen, was ich sagte. So viele Ideen, für immer verloren.',
    'story.p3': 'Deshalb habe ich Knner gebaut — ein Diktierwerkzeug, das offline funktioniert, den Datenschutz respektiert und mir erlaubt, Gedanken mit Sprechgeschwindigkeit zu erfassen.',
    'languages.title': '100 Sprachen Unterstützt',
    'languages.desc': 'Knner versteht Sie in Ihrer bevorzugten Sprache. Wechseln Sie nahtlos zwischen Sprachen ohne Einstellungen zu ändern.',
    'download.title': 'Knner Herunterladen',
    'download.desc': 'Verfügbar für Windows, macOS und Linux. Beginnen Sie in Sekunden zu diktieren.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Demnächst',
    'contact.title': 'Kontakt',
    'contact.desc': 'Fragen oder Feedback? Ich würde gerne von Ihnen hören.',
    'contact.email': 'Email',
    'contact.message': 'Nachricht',
    'contact.send': 'Senden',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Datenschutz',
    'social.users': '10.000+ Benutzer weltweit',
    'social.languages': '100+ Sprachen unterstützt',
    'social.offline': '100% Offline-fähig',
    'social.rating': '4,9 Benutzerbewertung',
    'social.testimonials': 'Was Benutzer sagen',
    'social.localData': 'Lokale Datenspeicherung',
    'social.noCloud': 'Nie in die Cloud hochgeladen',
    'social.madeHK': 'Hergestellt in Hong Kong',
    'social.securePayment': 'Sichere Zahlung',
    'screenshots.title': 'Screenshot-Vorschau',
    'screenshots.desc': 'So steigert Knner Ihre Produktivität',
    'screenshots.main': 'Hauptoberfläche',
    'screenshots.mainDesc': 'Klare Oberfläche, Ein-Tasten-Aufnahme',
    'screenshots.settings': 'Einstellungen',
    'screenshots.settingsDesc': 'Sprache, Hotkeys, Shortcuts anpassen',
    'screenshots.usage': 'Nutzungsverfolgung',
    'screenshots.usageDesc': 'Klare Anzeige der Nutzungslimits',
    'screenshots.floating': 'Floating Ball Modus',
    'screenshots.floatingDesc': 'Jederzeit aufnehmen, nie im Weg',
    'screenshots.screenshotTip': 'Empfohlene Größe: 1920x1080 (16:9)',
    'video.title': 'Sehen Sie wie schnell',
    'video.desc': '30 Sekunden um Knners Leistung zu verstehen',
    'video.play': '▶ 30s Intro-Video abspielen',
    'video.script': 'Video-Skript (30 Sekunden)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'Unglaublich! Meetings sind jetzt viel effizienter. Ich diktiere alles während ich spreche.',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': 'Perfekt für Vorlesungsnotizen. Ich kann dem Professor folgen ohne Details zu verlieren.',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'Liebe diese App! Sie hat Tippen für mich komplett ersetzt. Die Genauigkeit ist erstaunlich.',
  },
  pt: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Ditado Local First',
    'hero.tagline': '100% Offline • Privacidade • 4–8x Mais Rápido',
    'hero.cta': 'Obter Knner',
    'hero.downloadNow': 'Baixar Agora',
    'offline.title': 'Funciona Sem Internet',
    'offline.desc': 'Sem Wi-Fi? Sem problema. Knner processa tudo localmente no seu dispositivo. Perfeito para voos, locais remotos ou qualquer lugar com conexão ruim.',
    'privacy.title': 'Sua Voz É Sua',
    'privacy.desc': 'Sem chaves API. Sem upload na nuvem. Nenhum dado sai do seu computador. Seus pensamentos permanecem completamente privados, para sempre.',
    'efficiency.title': '4–8x Mais Rápido Que Digitar',
    'efficiency.desc': 'Fale naturalmente a 150+ palavras por minuto. Deixe suas ideias fluírem sem esperar seus dedos acompanharem.',
    'story.title': 'A História',
    'story.p1': 'Sou um amante de tecnologia que passa horas digitando todos os dias. Meus pulsos doem. Minhas ideias escapam enquanto meus dedos lutam para acompanhar.',
    'story.p2': 'Com TDAH, meu cérebro salta de pensamento em pensamento. Quando tenho um pensamento, mãos no teclado, já esqueci o que estava dizendo. Tantas ideias, perdidas para sempre.',
    'story.p3': 'Por isso construí o Knner — uma ferramenta de ditado que funciona offline, respeita a privacidade e me permite capturar pensamentos na velocidade da fala.',
    'languages.title': '100 Idiomas Suportados',
    'languages.desc': 'Knner entende você em seu idioma preferido. Alterne entre idiomas sem alterar configurações.',
    'download.title': 'Baixar Knner',
    'download.desc': 'Disponível para Windows, macOS e Linux. Comece a ditar em segundos.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Em Breve',
    'contact.title': 'Contato',
    'contact.desc': 'Perguntas ou feedback? Adoraria ouvir de você.',
    'contact.email': 'Email',
    'contact.message': 'Mensagem',
    'contact.send': 'Enviar',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacidade',
    'social.users': '10.000+ utilizadores em todo o mundo',
    'social.languages': 'Mais de 100 idiomas suportados',
    'social.offline': '100% funciona offline',
    'social.rating': 'Avaliação 4.9 utilizadores',
    'social.testimonials': 'O que dizem os utilizadores',
    'social.localData': 'Armazenamento local de dados',
    'social.noCloud': 'Nunca sobe para a cloud',
    'social.madeHK': 'Feito em Hong Kong',
    'social.securePayment': 'Pagamento seguro',
    'screenshots.title': 'Pré-visualização de capturas',
    'screenshots.desc': 'Veja como o Knner aumenta sua produtividade',
    'screenshots.main': 'Interface principal',
    'screenshots.mainDesc': 'Interface limpa, gravação com um toque',
    'screenshots.settings': 'Página de configurações',
    'screenshots.settingsDesc': 'Personalize idioma, atalhos de teclado',
    'screenshots.usage': 'Monitorização de uso',
    'screenshots.usageDesc': 'Exibição clara dos limites de uso',
    'screenshots.floating': 'Modo bola flutuante',
    'screenshots.floatingDesc': 'Grave a qualquer momento, sem incomodar',
    'screenshots.screenshotTip': 'Tamanho recomendado: 1920x1080 (16:9)',
    'video.title': 'Veja como é rápido',
    'video.desc': '30 segundos para entender o poder do Knner',
    'video.play': '▶ Clique para reproduzir vídeo de 30s',
    'video.script': 'Guion do vídeo (30 segundos)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'Incrível! As reuniões agora são muito mais eficientes. Dito tudo enquanto falo.',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': 'Perfeito para tomar notas na aula. Posso acompanhar o professor sem perder nenhum detalhe.',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'Adoro este app! Substituiu completamente minha digitação para escrever artigos.',
  },
  ru: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Локальный Диктант',
    'hero.tagline': '100% Офлайн • Конфиденциальность • В 4–8 раз Быстрее',
    'hero.cta': 'Получить Knner',
    'hero.downloadNow': 'Скачать сейчас',
    'offline.title': 'Работает Без Интернета',
    'offline.desc': 'Нет Wi-Fi? Нет проблемы. Knner обрабатывает всё локально на вашем устройстве. Идеально для полётов, удалённых мест или где плохая связь.',
    'privacy.title': 'Ваш Голос Принадлежит Вам',
    'privacy.desc': 'Нет API-ключей. Нет загрузки в облако. Данные не покидают ваш компьютер. Ваши мысли остаются полностью приватными, навсегда.',
    'efficiency.title': 'В 4–8 раз Быстрее Печати',
    'efficiency.desc': 'Говорите естественно со скоростью 150+ слов в минуту. Позвольте вашим идеям течь, не дожидаясь пальцев.',
    'story.title': 'История',
    'story.p1': 'Я любитель технологий, который каждый день часами печатает. У меня болят запястья. Мои идеи ускользают, пока пальцы с трудом поспевают.',
    'story.p2': 'С СДВГ мой мозг прыгает от мысли к мысли. Когда у меня есть мысль, руки на клавиатуре, я уже забыл, что говорил. Столько идей, потерянных навсегда.',
    'story.p3': 'Поэтому я создал Knner — инструмент диктовки, который работает офлайн, уважает конфиденциальность и позволяет мне захватывать мысли со скоростью речи.',
    'languages.title': '100 Языков Поддерживается',
    'languages.desc': 'Knner понимает вас на вашем предпочтительном языке. Переключайтесь между языками без изменения настроек.',
    'download.title': 'Скачать Knner',
    'download.desc': 'Доступно для Windows, macOS и Linux. Начните диктовать за секунды.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Скоро',
    'contact.title': 'Контакт',
    'contact.desc': 'Вопросы или отзывы? Буду рад услышать вас.',
    'contact.email': 'Email',
    'contact.message': 'Сообщение',
    'contact.send': 'Отправить',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacy',
    'social.users': '10,000+ пользователей по всему миру',
    'social.languages': 'Более 100 поддерживаемых языков',
    'social.offline': '100% работает офлайн',
    'social.rating': 'Рейтинг пользователей 4.9',
    'social.testimonials': 'Отзывы пользователей',
    'social.localData': 'Локальное хранение данных',
    'social.noCloud': 'Никогда не загружается в облако',
    'social.madeHK': 'Сделано в Гонконге',
    'social.securePayment': 'Безопасная оплата',
    'screenshots.title': 'Предпросмотр скриншотов',
    'screenshots.desc': 'Узнайте как Knner повышает продуктивность',
    'screenshots.main': 'Главный интерфейс',
    'screenshots.mainDesc': 'Чистый интерфейс, запись одним касанием',
    'screenshots.settings': 'Страница настроек',
    'screenshots.settingsDesc': 'Настройте язык, горячие клавиши, сокращения',
    'screenshots.usage': 'Отслеживание использования',
    'screenshots.usageDesc': 'Четкое отображение лимитов',
    'screenshots.floating': 'Режим плавающего шара',
    'screenshots.floatingDesc': 'Записывайте когда угодно, не мешает',
    'screenshots.screenshotTip': 'Рекомендуемый размер: 1920x1080 (16:9)',
    'video.title': 'Посмотрите как быстро',
    'video.desc': '30 секунд чтобы понять возможности Knner',
    'video.play': '▶ Нажмите для воспроизведения 30с видео',
    'video.script': 'Сценарий видео (30 секунд)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'Невероятно! Встречи стали намного эффективнее. Диктую всё во время разговора.',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': 'Идеально для конспектов на лекциях. Могу следить за преподавателем не теряя деталей.',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'Обожаю это приложение! Оно полностью заменило мне набор текста для статей.',
  },
  it: {
    'hero.title': 'Knner',
    'hero.subtitle': 'Dettato Local First',
    'hero.tagline': '100% Offline • Privacy • 4–8x Più Veloce',
    'hero.cta': 'Ottieni Knner',
    'hero.downloadNow': 'Scarica Ora',
    'offline.title': 'Funziona Senza Internet',
    'offline.desc': 'Niente Wi-Fi? Nessun problema. Knner elabora tutto localmente sul tuo dispositivo. Perfetto per voli, luoghi remoti o ovunque la connessione sia scarsa.',
    'privacy.title': 'La Tua Voce È Tua',
    'privacy.desc': 'Nessuna chiave API. Nessun caricamento cloud. Nessun dato lascia il tuo computer. I tuoi pensieri rimangono completamente privati, per sempre.',
    'efficiency.title': '4–8x Più Veloce Della Digitazione',
    'efficiency.desc': 'Parla naturalmente a 150+ parole al minuto. Lascia che le tue idee scorrano senza aspettare che le dita ti raggiungano.',
    'story.title': 'La Storia',
    'story.p1': 'Sono un amante della tecnologia che passa ore a digitare ogni giorno. Mi fanno male i polsi. Le mie idee scappano mentre le dita faticano a stare al passo.',
    'story.p2': 'Con l\'ADHD, il mio cervello salta da un pensiero all\'altro. Quando ho un pensiero, mani sulla tastiera, ho già dimenticato cosa stavo dicendo. Tante idee, perse per sempre.',
    'story.p3': 'Ecco perché ho costruito Knner — uno strumento di dettato che funziona offline, rispetta la privacy e mi permette di catturare i pensieri alla velocità della parola.',
    'languages.title': '100 Lingue Supportate',
    'languages.desc': 'Knner ti capisce nella tua lingua preferita. Passa da una lingua all\'altra senza modificare le impostazioni.',
    'download.title': 'Scarica Knner',
    'download.desc': 'Disponibile per Windows, macOS e Linux. Inizia a dettare in pochi secondi.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': 'Prossimamente',
    'contact.title': 'Contatto',
    'contact.desc': 'Domande o feedback? Mi piacerebbe sentirti.',
    'contact.email': 'Email',
    'contact.message': 'Messaggio',
    'contact.send': 'Invia',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': 'Local First • Privacy',
    'social.users': '10.000+ utenti in tutto il mondo',
    'social.languages': '100+ lingue supportate',
    'social.offline': '100% funziona offline',
    'social.rating': 'Valutazione 4.9 utenti',
    'social.testimonials': 'Cosa dicono gli utenti',
    'social.localData': 'Archiviazione dati locale',
    'social.noCloud': 'Mai caricato sul cloud',
    'social.madeHK': 'Fatto a Hong Kong',
    'social.securePayment': 'Pagamento sicuro',
    'screenshots.title': 'Anteprima screenshot',
    'screenshots.desc': 'Scopri come Knner aumenta la produttività',
    'screenshots.main': 'Interfaccia principale',
    'screenshots.mainDesc': 'Interfaccia pulita, registrazione con un tocco',
    'screenshots.settings': 'Pagina impostazioni',
    'screenshots.settingsDesc': 'Personalizza lingua, tasti rapidi, scorciatoie',
    'screenshots.usage': 'Tracciamento utilizzo',
    'screenshots.usageDesc': 'Chiaro display dei limiti di utilizzo',
    'screenshots.floating': 'Modalità palla flottante',
    'screenshots.floatingDesc': 'Registra sempre, senza intralciare',
    'screenshots.screenshotTip': 'Dimensione consigliata: 1920x1080 (16:9)',
    'video.title': 'Guarda quanto è veloce',
    'video.desc': '30 secondi per capire il potere di Knner',
    'video.play': '▶ Clicca per riprodurre il video introduttivo di 30s',
    'video.script': 'Script video (30 secondi)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': 'Incredibile! Le riunioni sono diventate molto più efficienti. Dettato tutto mentre parlo.',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': 'Perfetto per prendere appunti a lezione. Posso seguire il professore senza perdere nessun dettaglio.',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': 'Adoro questa app! Ha completamente sostituito la mia digitazione per scrivere articoli.',
  },
  ko: {
    'hero.title': 'Knner',
    'hero.subtitle': '로컬 퍼스트 음성 입력',
    'hero.tagline': '100% 오프라인 • 개인정보 보호 • 4–8배 빠름',
    'hero.cta': 'Knner 받기',
    'hero.downloadNow': '지금 다운로드',
    'offline.title': '인터넷 없이 작동',
    'offline.desc': 'Wi-Fi가 없어도 문제없습니다. Knner는 기기에서 모든 것을 로컬로 처리합니다. 비행, 원격 위치 또는 연결이 불량한 곳에 완벽합니다.',
    'privacy.title': '당신의 목소리는 당신의 것',
    'privacy.desc': 'API 키 없음. 클라우드 업로드 없음. 데이터가 컴퓨터를 떠나지 않습니다. 당신의 생각은 영원히 완전히 비공개로 유지됩니다.',
    'efficiency.title': '타이핑보다 4–8배 빠름',
    'efficiency.desc': '분당 150단어 이상으로 자연스럽게 말하세요. 손가락을 기다리지 않고 아이디어가 자유롭게 흐르게 하세요.',
    'story.title': '이야기',
    'story.p1': '저는 매일 수 시간 동안 타이핑하는 기술 애호가입니다. 손목이 아픕니다. 손가락이 따라가기 위해 힘쓰는 동안 아이디어가 사라집니다.',
    'story.p2': 'ADHD로 인해 제 뇌는 생각에서 생각으로 뛰어다닙니다. 생각이 떠오를 때, 키보드에 손을 올려놓으면, 이미 무엇을 말하고 있었는지 잊어버립니다. 너무 많은 아이디어가 영원히 사라졌습니다.',
    'story.p3': '그래서 저는 Knner를 만들었습니다 — 오프라인으로 작동하고, 개인정보를 존중하며, 말하는 속도로 생각을 포착할 수 있는 음성 입력 도구입니다.',
    'languages.title': '100개 언어 지원',
    'languages.desc': 'Knner는 선호하는 언어로 당신을 이해합니다. 설정을 변경하지 않고 언어 간에 원활하게 전환하세요.',
    'download.title': 'Knner 다운로드',
    'download.desc': 'Windows, macOS 및 Linux에서 사용 가능합니다. 몇 초 만에 음성 입력을 시작하세요.',
    'download.windows': 'Windows',
    'download.macos': 'macOS',
    'download.linux': 'Linux',
    'download.soon': '곧 출시',
    'contact.title': '연락처',
    'contact.desc': '질문이나 피드백이 있으신가요? 연락을 기다리겠습니다.',
    'contact.email': '이메일',
    'contact.message': '메시지',
    'contact.send': '병내기',
    'footer.copyright': 'Knner © 2026',
    'footer.tagline': '로컬 퍼스트 • 개인정보 보호',
    'social.users': '전 세계 사용자 10,000+',
    'social.languages': '100개 이상 언어 지원',
    'social.offline': '100% 오프라인 작동',
    'social.rating': '사용자 평점 4.9',
    'social.testimonials': '사용자 후기',
    'social.localData': '로컬 데이터 저장',
    'social.noCloud': '클라우드에 절대 업로드 안 함',
    'social.madeHK': '홍콩 제작',
    'social.securePayment': '안전한 결제',
    'screenshots.title': '스크린샷 미리보기',
    'screenshots.desc': 'Knner가 생산성을 높이는 방법',
    'screenshots.main': '메인 인터페이스',
    'screenshots.mainDesc': '깔끔한 인터페이스, 원터치 녹음',
    'screenshots.settings': '설정 페이지',
    'screenshots.settingsDesc': '언어, 단축키, 핫키 커스터마이즈',
    'screenshots.usage': '사용량 추적',
    'screenshots.usageDesc': '명확한 사용량 제한 표시',
    'screenshots.floating': '플로팅 Ball 모드',
    'screenshots.floatingDesc': '언제든 녹음, 방해 안 됨',
    'screenshots.screenshotTip': '권장 크기: 1920x1080 (16:9)',
    'video.title': '얼마나 빠른지 확인',
    'video.desc': '30초 만에 Knner의 힘을 알아보세요',
    'video.play': '▶ 30초 소개 영상 재생',
    'video.script': '영상 台本 (30초)',
    'testimonial1.name': 'Alex',
    'testimonial1.role': 'Software Engineer',
    'testimonial1.content': '오프라인에서도 잘 작동해서 정말 좋아요! 출장 중에도 정확하게 변환해줍니다',
    'testimonial2.name': 'Jordan',
    'testimonial2.role': 'University Student',
    'testimonial2.content': '강의 노트 필기에 완벽해요. 교수님의 말씀을 하나도 빼먹지 않고 기록할 수 있어요',
    'testimonial3.name': 'Taylor',
    'testimonial3.role': 'Content Creator',
    'testimonial3.content': '이 앱 정말 좋아요! 글 작성 시 타이핑을 완전히 대체했어요. 정확도가 놀라워요',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}